version: 0.2

phases:
  install:
    commands:
      - echo "[+] Scanning for security vulnerability within dependencies"
      - python --version
      - pip --version
  pre_build:
    commands:
      - echo "[+] Running tests..."
      # - flake8 --statistics
      # - python -m pytest tests/ -v
  build:
    commands:
      - echo "[+] Installing dependencies...."
      - pip install -r requirements.txt
  post_build:
    commands:
      - echo "build complete on `date`"
      
cache:
  paths:
    - '/root/.cache/pip'